project:
  type: website
  output-dir: docs

website:
  title: "Rohan Alexander"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "CV"
        href: cv-academic-Rohan_Alexander.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



