project:
  type: website
  output-dir: docs

website:
  title: "Sehar Bajwa"
  navbar:
    left:
      - text: "CV"
        href: uxresearch.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



